### ISSUE TITLE
Error from Console

### ISSUE THREAD

**Issue by ghost** [MinecraftWars/EnderPearlCooldown#9]
This error message comes up on the console, normally after every restart, about every 30 seconds or some randomized time.

`[03:58:46 WARN]: [EnderPearlCoolDown] Plugin EnderPearlCoolDown v1.5.0 generated an exception while executing task 90
java.lang.NoSuchMethodError: 'org.bukkit.entity.Player[] org.bukkit.Server.getOnlinePlayers()'
        at org.gestern.mcstats.MetricsLite.postPlugin(MetricsLite.java:285) ~[EnderPearlCooldown-1.5.0.jar:?]
        at org.gestern.mcstats.MetricsLite.access$200(MetricsLite.java:51) ~[EnderPearlCooldown-1.5.0.jar:?]
        at org.gestern.mcstats.MetricsLite$1.run(MetricsLite.java:173) ~[EnderPearlCooldown-1.5.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2006]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.1.jar:git-Purpur-2006]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by FPIU** [comment]
sir this is a plugin from 2012, it wont work on 1.20.1
